### PR TITLE
Fixes for Node 12.

### LINKED ISSUE #409: Unresolved External Symbols with Node 12
I've updated my nodejs installation to v12.2.0, and now I get a huge error while compiling an extension that worked fine previously.

```
          libneon_runtime-388232a462956889.rlib(neon.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) protected: static class v8::internal::Object * * __cdecl v8::HandleScope::CreateHandle(class v8::internal::Isolate *,class v8::internal::Object *)" (__imp_?CreateHandle@HandleScope@v8@@KAPEAPEAVObject@internal@2@PEAVIsolate@42@PEAV342@@Z) referenced in function "void __cdecl neon::complete_task(struct uv_work_s *)" (?complete_task@neon@@YAXPEAUuv_work_s@@@Z)
          libneon_runtime-388232a462956889.rlib(neon.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) private: class v8::internal::Object * * __cdecl v8::EscapableHandleScope::Escape(class v8::internal::Object * *)" (__imp_?Escape@EscapableHandleScope@v8@@AEAAPEAPEAVObject@internal@2@PEAPEAV342@@Z) referenced in function Neon_Convert_ToObject
          libneon_runtime-388232a462956889.rlib(neon.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: int __cdecl v8::String::Utf8Length(void)const " (__imp_?Utf8Length@String@v8@@QEBAHXZ) referenced in function Neon_String_Utf8Length
          libneon_runtime-388232a462956889.rlib(neon.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class v8::Local<class v8::Function> __cdecl v8::FunctionTemplate::GetFunction(void)" (__imp_?GetFunction@FunctionTemplate@v8@@QEAA?AV?$Local@VFunction@v8@@@2@XZ) referenced in function Neon_Class_Constructor
          libneon_runtime-388232a462956889.rlib(neon.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) private: static class v8::internal::Object * * __cdecl v8::V8::GlobalizeReference(class v8::internal::Isolate *,class v8::internal::Object * *)" (__imp_?GlobalizeReference@V8@v8@@CAPEAPEAVObject@internal@2@PEAVIsolate@42@PEAPEAV342@@Z) referenced in function "public: virtual void __cdecl neon::BaseClassMetadata::construct(class v8::FunctionCallbackInfo<class v8::Value> const &)" (?construct@BaseClassMetadata@neon@@UEAAXAEBV?$FunctionCallbackInfo@VValue@v8@@@v8@@@Z)
          libneon_runtime-388232a462956889.rlib(neon.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) private: static void __cdecl v8::V8::DisposeGlobal(class v8::internal::Object * *)" (__imp_?DisposeGlobal@V8@v8@@CAXPEAPEAVObject@internal@2@@Z) referenced in function "protected: virtual __cdecl neon::ClassMetadata::~ClassMetadata(void)" (??1ClassMetadata@neon@@MEAA@XZ)
          libneon_runtime-388232a462956889.rlib(neon.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) private: static void __cdecl v8::V8::MakeWeak(class v8::internal::Object * *,void *,void (__cdecl*)(class v8::WeakCallbackInfo<void> const &),enum v8::WeakCallbackType)" (__imp_?MakeWeak@V8@v8@@CAXPEAPEAVObject@internal@2@PEAXP6AXAEBV?$WeakCallbackInfo@X@2@@ZW4WeakCallbackType@2@@Z) referenced in function "public: virtual void __cdecl neon::BaseClassMetadata::construct(class v8::FunctionCallbackInfo<class v8::Value> const &)" (?construct@BaseClassMetadata@neon@@UEAAXAEBV?$FunctionCallbackInfo@VValue@v8@@@v8@@@Z)
```

I assume this is because of some deprecated functionality, or maybe a header just needs updating. I'm not quite sure. Could be related to #202 ? 

If it's relevant, I'm compiling on Windows 10, with MSVC 2019.

### PR DESCRIPTION
**Pull request by kjvalencik**
Resolves #409. There are still warnings that should be resolved. Especially, `MakeCallback`, which will break domain support.

### CODE REVIEW

**Comment by kjvalencik** [comment]
Failed build, but it worked locally for me. This may require bumping the `nan` version.

**Comment by Abdillah** [comment]
It worked with latest node v12.0 and build-able locally. Unfortunately, the resulting lib (after compiling the `neon-runtime`) still contains missing symbols (as the original bug report stated). Any hint? I am interested in helping.

```
$ /home/user/.nvm/versions/node/v12.0.0/bin/electron ../lib/index.js
Error: /home/user/workspace/neonproject/native/index.node: undefined symbol: _ZN2v811HandleScope12CreateHandleEPNS_8internal7IsolateEPNS1_6ObjectE
    at process.func [as dlopen] (electron/js2c/asar.js:155:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:850:18)
    at Object.func [as .node] (electron/js2c/asar.js:155:31)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/user/workspace/lib/index.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
```

# Versions
```
$ /home/user/.nvm/versions/node/v12.0.0/bin/electron -v
v5.0.2
$ node -v
v12.0.0
$ npm -v
6.9.0
```

**Comment by Abdillah** [comment]
Oh, seems my case above is a runtime problem. Using this patch compilation is working fine. But, something in my system prevent the module from being loaded successfully. Thanks.

**Comment by kjvalencik** [comment]
@Abdillah Thanks for the reminder that I needed to update my PR to include the latest `nan`!

**Comment by kjvalencik** [comment]
@dherman Can we merge / release this?
